sources:
  - name: sources_adventure_works
    description: Data source from Adventure Works
    schema: raw_adventure_works
    database: fea24_11
    tables:
      - name: salesorderheader
        columns:
          - name: salesorderid
            data_tests:
              - unique
              - not_null
      - name: salesorderdetail
      - name: product
        columns:
          - name: productid
            data_tests:
              - unique
              - not_null
      - name: productcategory
        columns:
          - name: productcategoryid
            data_tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: productsubcategoryid
            data_tests:
              - unique
              - not_null
      - name: customer
        columns:  
          - name: customerid
            data_tests:
              - unique 
              - not_null
      - name: person
        columns:  
          - name: businessentityid
            data_tests:
              - unique 
              - not_null      
      - name: salesorderheadersalesreason
        columns:
          - name: salesorderid
          - name: salesreasonid
            data_tests:
              - unique 
              - not_null
      - name: salesreason
        columns:
          - name: salesreasonid
            data_tests:
              - unique 
              - not_null        
      - name: creditcard
        columns:
          - name: creditcardid
            data_tests:
              - unique 
              - not_null 
